import { useState, useMemo } from 'react'
import ContestantCard from './ContestantCard'
import GlobalTimer from './GlobalTimer'
import type { RankedContestant, Contestant } from '../types'
interface Props { rankedContestants: RankedContestant[]; contestStartTime: number; now: number; durationMs: number; onFinish: (id: string) => void; onDisqualify: (id: string) => void; onReset: () => void; isAdmin: boolean; onEditContestant: (id: string, patch: Partial<Contestant>) => void }
export default function Arena({ rankedContestants, contestStartTime, now, durationMs, onFinish, onDisqualify, onReset, isAdmin, onEditContestant }: Props) {
  const [showResetConfirm, setShowResetConfirm] = useState(false); const [search, setSearch] = useState(''); const elapsedMs = now - contestStartTime; const contestOver = elapsedMs >= durationMs; const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return q ? rankedContestants.filter(c => c.name.toLowerCase().includes(q)) : rankedContestants }, [rankedContestants, search]); const finished = filtered.filter(c => c.finishedAt); const active = filtered.filter(c => !c.finishedAt && !c.disqualified && !contestOver); const failed = filtered.filter(c => c.disqualified || (!c.finishedAt && contestOver));
  const card = (c: RankedContestant, rank: number | null) => <ContestantCard key={c.id} contestant={c} rank={rank} elapsedMs={elapsedMs} durationMs={durationMs} onFinish={onFinish} onDisqualify={onDisqualify} isAdmin={isAdmin} onEdit={onEditContestant} />
  return <div className="arena-screen"><GlobalTimer elapsedMs={elapsedMs} durationMs={durationMs} contestOver={contestOver} />{rankedContestants.length >= 5 && <div className="search-bar-wrap"><div className="search-bar"><span className="search-icon">Søk</span><input className="search-input" placeholder="Søk efter en Kriger..." value={search} onChange={e => setSearch(e.target.value)} /></div></div>}{finished.length > 0 && <section className="arena-section"><h2 className="section-title glory">Ærens Hal</h2><div className="cards-grid">{finished.map((c, i) => card(c, i + 1))}</div></section>}{active.length > 0 && <section className="arena-section"><h2 className="section-title active-title">Drikker Endnu</h2><div className="cards-grid">{active.map(c => card(c, null))}</div></section>}{failed.length > 0 && <section className="arena-section"><h2 className="section-title shame">Hestemann</h2><div className="cards-grid">{failed.map(c => card(c, null))}</div></section>}<div className="arena-footer">{!showResetConfirm ? <button className="medieval-btn reset-btn" onClick={() => setShowResetConfirm(true)}>Afslut og gem Faxing</button> : <div className="confirm-reset"><p>Er I visse? Fremgangen gemmes i krøniken.</p><div className="confirm-btns"><button className="medieval-btn danger-btn" onClick={onReset}>Ja, gem Faxingen</button><button className="medieval-btn" onClick={() => setShowResetConfirm(false)}>Fortsæt</button></div></div>}</div></div>
}
