import { useState } from 'react'
import type { FaxingEvent, RankedContestant } from '../types'

interface Props { event: FaxingEvent; isAdmin: boolean; onBack: () => void; onSave: (event: FaxingEvent) => Promise<void>; onDelete: (id: string) => Promise<void> }
const formatTime = (ms: number) => `${Math.floor(ms / 60000)}:${String(Math.floor((ms % 60000) / 1000)).padStart(2, '0')}`
const formatDate = (date: number) => new Intl.DateTimeFormat('da-DK', { day: 'numeric', month: 'long', year: 'numeric' }).format(date)
export default function EventView({ event, isAdmin, onBack, onSave, onDelete }: Props) {
  const [draft, setDraft] = useState(event); const [saving, setSaving] = useState(false)
  const update = (id: string, patch: Partial<RankedContestant>) => setDraft(v => ({ ...v, contestants: v.contestants.map(c => c.id === id ? { ...c, ...patch } : c) }))
  const save = async () => { setSaving(true); try { await onSave(draft) } finally { setSaving(false) } }
  return <div className="event-view scroll-panel"><button className="back-link" onClick={onBack}>Tilbage til krøniken</button>{isAdmin ? <div className="admin-edit-form"><label>Eventnavn<input className="medieval-input" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Dato<input className="medieval-input" type="date" value={new Date(draft.date).toISOString().slice(0, 10)} onChange={e => setDraft({ ...draft, date: new Date(`${e.target.value}T12:00:00`).getTime() })} /></label><label className="check-label"><input type="checkbox" checked={draft.official} onChange={e => setDraft({ ...draft, official: e.target.checked })} /> Officiel Faxing</label></div> : <><p className="event-date">{formatDate(event.date)} · {event.official ? 'Officiel Faxing' : 'Anden begivenhed'}</p><h2 className="panel-title">{event.name}</h2></>}<p className="panel-desc">{draft.contestants.length} deltagere i denne dyst.</p><div className="results-list">{draft.contestants.map((c, index) => <div className={`result-row ${c.title === 'Faxekonge' || c.title === 'Faxedronning' ? 'royal-result' : ''}`} key={c.id}><span className="result-rank">{index + 1}</span>{isAdmin ? <><input className="medieval-input admin-name-input" value={c.name} onChange={e => update(c.id, { name: e.target.value })} /><select className="medieval-input admin-status" value={c.disqualified ? 'out' : c.finishedAt ? 'done' : 'active'} onChange={e => update(c.id, e.target.value === 'out' ? { disqualified: true, finishedAt: null } : e.target.value === 'done' ? { disqualified: false, finishedAt: c.finishedAt ?? draft.date + c.elapsed } : { disqualified: false, finishedAt: null })}><option value="done">Færdig</option><option value="active">Ikke færdig</option><option value="out">Hestemann</option></select></> : <span className="result-name">{c.name}</span>}<strong>{c.title === 'Hestemann' || c.disqualified ? 'Hestemann' : formatTime(c.elapsed)}</strong>{(c.title === 'Faxekonge' || c.title === 'Faxedronning') && <small>{c.title}</small>}</div>)}</div>{isAdmin && <div className="admin-actions"><button className="medieval-btn" disabled={saving} onClick={save}>{saving ? 'Gemmer...' : 'Gem ændringer'}</button><button className="medieval-btn danger-btn" onClick={() => { if (window.confirm('Slet denne faxing?')) void onDelete(event.id) }}>Slet faxing</button></div>}</div>
}
