import { useState } from 'react'
import type { FaxingEvent, RankedContestant } from '../types'

interface Props { event: FaxingEvent; isAdmin: boolean; onBack: () => void; onSave: (event: FaxingEvent) => Promise<void>; onDelete: (id: string) => Promise<void> }
const formatTime = (ms: number) => `${Math.floor(ms / 60000)}:${String(Math.floor((ms % 60000) / 1000)).padStart(2, '0')}`
const formatDate = (date: number) => new Intl.DateTimeFormat('da-DK', { day: 'numeric', month: 'long', year: 'numeric' }).format(date)

export default function EventView({ event, isAdmin, onBack, onSave, onDelete }: Props) {
  const [draft, setDraft] = useState(event); const [saving, setSaving] = useState(false); const [view, setView] = useState<'timeline' | 'list'>('timeline')
  const [newName, setNewName] = useState(''); const [newGender, setNewGender] = useState<'male' | 'female'>('male'); const [newMinutes, setNewMinutes] = useState(''); const [newSeconds, setNewSeconds] = useState('')
  const update = (id: string, patch: Partial<RankedContestant>) => setDraft(v => ({ ...v, contestants: v.contestants.map(c => c.id === id ? { ...c, ...patch } : c) }))
  const addAttendee = () => { const name = newName.trim(); const minutes = Number(newMinutes); const seconds = Number(newSeconds || 0); if (!name || !Number.isInteger(minutes) || minutes < 0 || !Number.isInteger(seconds) || seconds < 0 || seconds > 59) return; const elapsed = (minutes * 60 + seconds) * 1000; setDraft(v => ({ ...v, contestants: [...v.contestants, { id: crypto.randomUUID(), name, gender: newGender, finishedAt: v.date, disqualified: false, title: null, elapsed }] })); setNewName(''); setNewMinutes(''); setNewSeconds('') }
  const save = async () => { setSaving(true); try { await onSave(draft) } finally { setSaving(false) } }
  const sorted = [...draft.contestants].sort((a, b) => (a.finishedAt ? a.elapsed : Number.MAX_SAFE_INTEGER) - (b.finishedAt ? b.elapsed : Number.MAX_SAFE_INTEGER))
  return <div className="event-view scroll-panel"><button className="back-link" onClick={onBack}>Tilbage til krøniken</button><div className="event-view-heading"><div>{isAdmin ? <div className="admin-edit-form"><label>Eventnavn<input className="medieval-input" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Dato<input className="medieval-input" type="date" value={new Date(draft.date).toISOString().slice(0, 10)} onChange={e => setDraft({ ...draft, date: new Date(`${e.target.value}T12:00:00`).getTime() })} /></label><label className="check-label"><input type="checkbox" checked={draft.official} onChange={e => setDraft({ ...draft, official: e.target.checked })} /> Officiel Faxing</label></div> : <><p className="event-date">{formatDate(event.date)} · {event.official ? 'Officiel ordenstvist' : 'Uofficiel samling'}</p><h2 className="panel-title">{event.name}</h2></>}</div></div><p className="panel-desc">{draft.contestants.length} deltagere i denne dyst.</p><div className="result-toolbar"><span>Resultater</span><div className="view-toggle" role="group" aria-label="Vis resultater som"><button className={view === 'timeline' ? 'view-toggle-btn active' : 'view-toggle-btn'} onClick={() => setView('timeline')}>Tidslinje</button><button className={view === 'list' ? 'view-toggle-btn active' : 'view-toggle-btn'} onClick={() => setView('list')}>Liste</button></div></div>{isAdmin && <div className="admin-add-attendee"><strong>Tilføj deltager til den historiske Faxing</strong><div className="admin-add-fields"><input className="medieval-input" placeholder="Navn" aria-label="Navn på ny deltager" value={newName} onChange={e => setNewName(e.target.value)} /><select className="medieval-input" aria-label="Køn på ny deltager" value={newGender} onChange={e => setNewGender(e.target.value as 'male' | 'female')}><option value="male">Mand</option><option value="female">Kvinde</option></select><input className="medieval-input time-input" inputMode="numeric" placeholder="Min" aria-label="Drikketid minutter" value={newMinutes} onChange={e => setNewMinutes(e.target.value)} /><input className="medieval-input time-input" inputMode="numeric" placeholder="Sek" aria-label="Drikketid sekunder" value={newSeconds} onChange={e => setNewSeconds(e.target.value)} /><button className="medieval-btn" onClick={addAttendee}>Tilføj</button></div></div>}<div className={view === 'timeline' ? 'results-list results-timeline' : 'results-list'}>{sorted.map((c, index) => <ResultRow key={c.id} contestant={c} index={index} isAdmin={isAdmin} onUpdate={update} />)}</div>{isAdmin && <div className="admin-actions"><button className="medieval-btn" onClick={save} disabled={saving}>{saving ? 'Gemmer…' : 'Gem ændringer'}</button><button className="medieval-btn danger-btn" onClick={() => { if (window.confirm('Slet denne Faxing permanent?')) onDelete(event.id) }}>Slet Faxing</button></div>}</div>
}

function ResultRow({ contestant: c, index, isAdmin, onUpdate }: { contestant: RankedContestant; index: number; isAdmin: boolean; onUpdate: (id: string, patch: Partial<RankedContestant>) => void }) {
  return <div className={`result-row ${c.title === 'Faxekonge' || c.title === 'Faxedronning' ? 'royal-result' : ''}`}><span className="result-rank">{index + 1}</span>{isAdmin ? <><input aria-label={`Navn på deltager ${index + 1}`} className="medieval-input admin-name-input" value={c.name} onChange={e => onUpdate(c.id, { name: e.target.value })} /><select aria-label={`Status for ${c.name}`} className="medieval-input admin-status" value={c.disqualified ? 'out' : c.finishedAt ? 'done' : 'active'} onChange={e => onUpdate(c.id, e.target.value === 'out' ? { disqualified: true, finishedAt: null } : e.target.value === 'done' ? { disqualified: false, finishedAt: c.finishedAt ?? Date.now() } : { disqualified: false, finishedAt: null })}><option value="done">Færdig</option><option value="active">Ikke færdig</option><option value="out">Hestemann</option></select></> : <span className="result-name">{c.name}</span>}<strong>{c.title === 'Hestemann' || c.disqualified ? 'Hestemann' : formatTime(c.elapsed)}</strong>{(c.title === 'Faxekonge' || c.title === 'Faxedronning') && <span className="royal-mark">{c.title}</span>}</div>
}
