import { useState, type FormEvent } from 'react'
import type { Contestant, Gender } from '../types'
interface RegistrationProps { contestants: Contestant[]; onAdd: (name: string, gender: Gender) => void; onRemove: (id: string) => void; onStart: (name: string, official: boolean, password?: string) => void; onHistory: () => void }
export default function Registration({ contestants, onAdd, onRemove, onStart, onHistory }: RegistrationProps) {
  const [name, setName] = useState(''); const [gender, setGender] = useState<Gender>('male'); const [eventName, setEventName] = useState(''); const [official, setOfficial] = useState(false); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  const handleAdd = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const trimmed = name.trim(); if (!trimmed) return setError('Et Navn er fornødent, tappre Sjæl.'); if (contestants.some(c => c.name.toLowerCase() === trimmed.toLowerCase())) return setError('Denne Kriger hath allerede indtaget Arenaen.'); onAdd(trimmed, gender); setName(''); setError('') }
  const handleStart = () => { const title = eventName.trim() || (official ? 'Officiel Faxing' : 'Faxing'); if (official && password.trim().length < 4) return setError('Officielle Faxinger kræver et password på mindst 4 tegn.'); onStart(title, official, password.trim()) }
  return <div className="registration-screen"><div className="scroll-panel"><div className="history-link-row"><button className="back-link" onClick={onHistory}>Se tidligere Faxinger →</button></div><h2 className="panel-title">⚜ Innskriv Eders Krigere ⚜</h2><p className="panel-desc">Hver Kriger maa fortære een Litre Faxe (10% Styrke) inden Timens Udløb. De som lykkes, hædres med Titelen <em>Faxeridder</em>. Den første Herre erholder Titelen <strong>Faxekonge</strong>, og den første Dame — <strong>Faxedronning</strong>.</p><form className="enlist-form" onSubmit={handleAdd}><div className="form-row"><input className="medieval-input" type="text" placeholder="Krigerens Navn..." value={name} onChange={e => { setName(e.target.value); setError('') }} maxLength={30} /><div className="gender-toggle"><button type="button" className={`gender-btn ${gender === 'male' ? 'active' : ''}`} onClick={() => setGender('male')}>♂ Herre</button><button type="button" className={`gender-btn ${gender === 'female' ? 'active' : ''}`} onClick={() => setGender('female')}>♀ Dame</button></div><button type="submit" className="medieval-btn enlist-btn">+ Innskriv</button></div>{error && <p className="form-error">{error}</p>}</form>{contestants.length > 0 && <div className="contestant-list"><h3 className="list-title">Innskrevne Krigere ({contestants.length})</h3><ul>{contestants.map(c => <li key={c.id} className="contestant-item"><span className="contestant-gender-icon">{c.gender === 'male' ? '♂' : '♀'}</span><span className="contestant-name">{c.name}</span><button className="remove-btn" onClick={() => onRemove(c.id)}>✕</button></li>)}</ul></div>}<div className="event-setup"><input className="medieval-input" placeholder="Begivenhedens navn..." value={eventName} onChange={e => setEventName(e.target.value)} /><label className="official-toggle"><input type="checkbox" checked={official} onChange={e => setOfficial(e.target.checked)} /> Officiel Faxing</label>{official && <input className="medieval-input" type="password" placeholder="Password til officiel Faxing" value={password} onChange={e => setPassword(e.target.value)} />}</div><div className="start-section"><button className="medieval-btn start-btn" onClick={handleStart} disabled={!contestants.length}>⚔ Begyn Kampen ⚔</button>{!contestants.length && <p className="start-hint">Innskriv mindst én Kriger for at begynde.</p>}</div></div></div>
}
